# Generated by Django 4.0.1 on 2022-02-21 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('A', 'Zona A'), ('B', 'Zona B'), ('C', 'Zona C'), ('D', 'Zona D')], max_length=1)),
                ('numero', models.IntegerField()),
                ('piso_nivel', models.CharField(choices=[('1', 'Primer Nivel'), ('2', 'Segundo Nivel'), ('3', 'Tercer Nivel')], max_length=1)),
                ('estado_disponibilidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=500)),
                ('Aforo_total', models.IntegerField()),
                ('Aforo_actual', models.IntegerField()),
                ('Image_sede', models.ImageField(upload_to='sede_images')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('Id_estacionamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.estacionamiento')),
                ('Id_sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.sede')),
            ],
        ),
    ]
