# Generated by Django 4.0.1 on 2022-02-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=500)),
                ('Aforo_total', models.IntegerField()),
                ('Aforo_actual', models.IntegerField()),
                ('Image_sede', models.ImageField(upload_to='sede_images')),
            ],
        ),
    ]
