# Generated by Django 4.0.1 on 2022-03-12 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estado_disponibilidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=500)),
                ('Aforo_total', models.IntegerField()),
                ('Aforo_actual', models.IntegerField()),
                ('Image_sede', models.ImageField(upload_to='sede_images')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('Pago', models.IntegerField()),
                ('Id_estacionamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.estacionamiento')),
                ('Id_sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.sede')),
                ('Id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='id_nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.niveles'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='id_zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.zona'),
        ),
    ]
